export const BASE_URL = "http://localhost:4000/api/v4" ;

export const LOGIN_REQUEST = "LOGIN_REQUEST" ;
export const LOGIN_SUCCESS = "LOGIN_SUCCESS" ;
export const LOGIN_FAIL =    "LOGIN_FAIL" ;

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST" ;
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS" ;
export const REGISTER_USER_FAIL =    "REGISTER_USER_FAIL" ;

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST" ;
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS" ;
export const LOAD_USER_FAIL =    "LOAD_USER_FAIL" ;

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS" ;
export const LOGOUT_USER_FAIL =    "LOGOUT_USER_FAIL" ;

export const CREATE_BRIDE_REQUEST = "CREATE_BRIDE_REQUEST";
export const CREATE_BRIDE_SUCCESS = "CREATE_BRIDE_SUCCESS";
export const CREATE_BRIDE_RESET = "CREATE_BRIDE_RESET";
export const CREATE_BRIDE_FAIL = "CREATE_BRIDE_FAIL";

export const CREATE_GROOM_REQUEST = "CREATE_GROOM_REQUEST";
export const CREATE_GROOM_SUCCESS = "CREATE_GROOM_SUCCESS";
export const CREATE_GROOM_RESET = "CREATE_GROOM_RESET";
export const CREATE_GROOM_FAIL = "CREATE_GROOM_FAIL";

export const CREATE_MARRIAGE_REQUEST = "CREATE_MARRIAGE_REQUEST";
export const CREATE_MARRIAGE_SUCCESS = "CREATE_MARRIAGE_SUCCESS";
export const CREATE_MARRIAGE_RESET = "CREATE_MARRIAGE_RESET";
export const CREATE_MARRIAGE_FAIL = "CREATE_MARRIAGE_FAIL";

export const EVENT_DETAILS_REQUEST = "EVENT_DETAILS_REQUEST";
export const EVENT_DETAILS_SUCCESS = "EVENT_DETAILS_SUCCESS";
export const EVENT_DETAILS_FAIL = "EVENT_DETAILS_FAIL";

export const ALL_EVENTS_REQUEST = "ALL_EVENTS_REQUEST";
export const ALL_EVENTS_SUCCESS = "ALL_EVENTS_SUCCESS";
export const ALL_EVENTS_FAIL = "ALL_EVENTS_FAIL";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST" ;
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS" ;
export const DELETE_EVENT_RESET = "DELETE_EVENT_RESET" ;
export const DELETE_EVENT_FAIL =    "DELETE_EVENT_FAIL" ;


export const CLEAR_ERRORS= "CLEAR_ERRORS" ;